name: Upload static files to $web container

on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: upload files to web container
        env: 
          azure_connection_string: ${{ secrets.STORAGE_ACCOUNT_CONNECTION_STRING }}
        uses: azure/cli@v2
        with:
          azcliversion: 2.30.0
          inlinescript: |
            az storage blob upload --connection-string "$azure_connection_string" -c '$web' -f ./index.html --overwrite --output none
            
      
